





df <- data.frame(
  NAME_E = c("Banc-des-Américains Marine Protected Area",    #i think if i was linking to the target it would be NAME_E = c(MPAs$NAME_E)
              "Basin Head Marine Protected Area",
              "Bay of Islands Salmon Migration Closure",
              "Beaugé Bank Sponge Conservation Area",
              "Central Gulf of St. Lawrence Coral Conservation Area",
              "Corsair and Georges Canyons Marine Refuge",
              "Division 3O Coral closure",
              "East of Anticosti Island Sponge Conservation Area",
              "Eastern Canyons Marine Refuge",
              "Eastern Gulf of St. Lawrence Coral Conservation Area",
              "Eastern Honguedo Strait Coral and Sponge Conservation Area",
              "Eastport – Duck Island Marine Protected Area",
              "Eastport – Round Island Marine Protected Area",
              "Emerald Basin and Sambro Bank Marine Refuge",
              "Funk Island Deep Closure",
              "Gully Marine Protected Area",
              "Hawke Channel Closure",
              "Hopedale Saddle Closure",
              "Jacques-Cartier Strait Sponge Conservation Area",
              "Jordan Basin Marine Refuge",
              "Laurentian Channel Marine Protected Area",
              "Les Demoiselles nursery (Plaisance Bay), Magdalen Islands Closure",
              "Lobster Area Closure (Gander Bay)",
              "Lobster Area Closure (Glovers Harbour)",
              "Lobster Area Closure (Gooseberry Island)",
              "Lobster Area Closure (Mouse Island)",
              "Lobster Area Closure (Penguin Islands)",
              "Lobster Area Closure (Shoal Point)",
              "Lobster Area Closure (Trout River)",
              "Magdalen Islands Lagoons Closures (6 Overlapping Closures)",
              "Miramichi Bay Closure",
              "Musquash Estuary Marine Protected Area",
              "North of Bennett Bank Coral Conservation Area",
              "Northeast Channel Marine Refuge",
              "Northeast Newfoundland Slope Closure",
              "Parent Bank Sponge Conservation Area",
              "Saguenay Fjord Upstream Closure",
              "Scallop Buffer Zone (SFA 22)",
              "Scallop Buffer Zone (SFA 24)",
              "Slope of Magdalen Shallows Coral Conservation Area",
              "South-East of Anticosti Island Sponge Conservation Area",
              "St. Anns Bank Marine Protected Area",
              "Western Honguedo Strait Coral Conservation Area",
              "Western and Emerald Banks Marine Refuge",
              "Non_Conservation_Area"
  ),

  date_of_establishment = c("2019",
                            "2005",
                            "1981",
                            "2017",
                            "2017",
                            "2016",
                            "2007",
                            "2017",
                            "2022",
                            "2017",
                            "2017",
                            "2005",
                            "2005",
                            "2016",
                            "2017",
                            "2004",
                            "2017",
                            "2017",
                            "2017",
                            "2016",
                            "2019",
                            "2016",
                            "1998",
                            "2004",
                            "1996",
                            "2004",
                            "2004",
                            "1998",
                            "2002",
                            "2014",
                            "1986",
                            "2006",
                            "2017",
                            "2016",
                            "2017",
                            "2017",
                            "1985",
                            "2017",
                            "2017",
                            "2017",
                            "2017",
                            "2017",
                            "2017",
                            "2017",
                            "N/A"
                            )

)

